services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: 'docker.io/dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: "a@b.com"
      PGADMIN_DEFAULT_PASSWORD: "123123"
    env_file:
      - ./app.env
    ports:
      - 15080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
volumes:
  postgres:
  pgadmin-data: